first_number = input("Enter your first number: ")
print("The first number is:",first_number)
second_number = input("Enter your second number: ")
print("The second number is:",second_number)
sum = int(first_number)+int(second_number)
subtraction = int(first_number)-int(second_number)
multiplication = int(first_number)*int(second_number)
division = int(first_number)/int(second_number)
print("sum", "subtraction", "multiplication","division")
print(sum, subtraction, multiplication,division)